# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

development:
  <<: *default
  database: enterprise-management_api_development

test:
  <<: *default
  database: enterprise-management_api_test

production:
  <<: *default
  database: enterprise-management_api_production
  username: enterprise-management_api
  password: <%= ENV['ENTERPRISE_MANAGEMENT_API_DATABASE_PASSWORD'] %>
